name: Staging Deployment
on:
  workflow_dispatch:
    inputs:
      droplet_1:
        description: 'Deploy on Droplet 1'
        required: true
        type: boolean
      droplet_3:
        description: 'Deploy on Droplet 3'
        required: true
        type: boolean
      environment:
        type: environment
      custom_task:
        description: 'Custom rake task for execution'
        required: false
        type: string

jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-latest
    environment: staging
    env:
      DROPLET_1_IP: ${{ secrets.DROPLET_1_IP }}
      DROPLET_3_IP: ${{ secrets.DROPLET_3_IP }}
      DEPLOY_DIGITAL_OCEAN: '~/.ssh/deploy-digital-ocean'
      DROPLET_1_ENABLED: ${{ github.event.inputs.droplet_1 }}
      DROPLET_3_ENABLED: ${{ github.event.inputs.droplet_3 }}

    steps:
    - name: Install SSH key to Server for Deploy User
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_DIGITAL_OCEAN }}
        name: deploy-digital-ocean
        known_hosts: unnecessary

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Deploy to staging
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/deploy-digital-ocean
        bundle exec cap staging deploy

    - name: Custom Task
      if: ${{ github.event.inputs.custom_task != null }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/deploy-digital-ocean
        bundle exec cap staging deploy:custom_task["${{ github.event.inputs.custom_task }}"]
