name: Staging Deployment
on: workflow_dispatch
jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Install SSH key to Server
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: github-actions
        known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
        config: |
          host ${{ secrets.SSH_HOST }}
            IdentityFile ~/.ssh/github-actions
            IdentitiesOnly yes
            ForwardAgent yes
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }}

    # - name: Checkout Repo
    #   uses: actions/checkout@v2

    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.4.1
    #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    # - name: Deploy to staging
    #   run: |
    #     eval "$(ssh-agent -s)"
    #     ssh-add ~/.ssh/github-actions
    #     bundle exec cap production deploy
