name: Tryouts
on: workflow_dispatch
jobs:
  Display-Added-Secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 'Print Test Secret'
        run: echo '${{ secrets.TEST_KEY }}'
